"""Add avatar to User

Revision ID: 519e624225a6
Revises: 1019553e2dc4
Create Date: 2025-04-16 18:20:07.424004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519e624225a6'
down_revision = '1019553e2dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
