"""фиксим slider_item

Revision ID: 6e06d19f827d
Revises: 519e624225a6
Create Date: 2025-04-23 14:14:37.435467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e06d19f827d'
down_revision = '519e624225a6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('slider_item') as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('news_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('image', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
        )
        op.add_column('slider_item', sa.Column('news_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'slider_item', 'news_item', ['news_id'], ['id'])
        op.drop_column('slider_item', 'link')
        # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('slider_item') as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('slider_item', sa.Column('link', sa.VARCHAR(length=200), nullable=True))
        op.drop_constraint(None, 'slider_item', type_='foreignkey')
        op.drop_column('slider_item', 'news_id')
        op.drop_table('news_item')
        # ### end Alembic commands ###
