"""add foreign key

Revision ID: d540619ee829
Revises: 8b66970387f3
Create Date: 2025-04-24 14:18:17.099086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd540619ee829'
down_revision = '8b66970387f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_item')
    with op.batch_alter_table('slider_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_slider_item_news_id', 'news', ['news_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slider_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_slider_item_news_id', type_='foreignkey')
        batch_op.drop_column('news_id')

    op.create_table('news_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
